"""apitoken

Revision ID: 0278e57b8712
Revises: 54dcdc267ce3
Create Date: 2025-12-20 11:13:07.938930

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0278e57b8712'
down_revision = '54dcdc267ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='api_token_pkey')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index('api_token_app_id_type_idx', ['app_id', 'type'], unique=False)
        batch_op.create_index('api_token_token_idx', ['token', 'type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index('api_token_token_idx')
        batch_op.drop_index('api_token_app_id_type_idx')

    op.drop_table('api_tokens')
    # ### end Alembic commands ###
