"""message agent thought

Revision ID: 1cfcb998da3f
Revises: b6d1b5ef4c06
Create Date: 2025-12-20 11:20:23.701366

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1cfcb998da3f'
down_revision = 'b6d1b5ef4c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_agent_thoughts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('message_chain_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('thought', sa.Text(), nullable=True),
    sa.Column('tool', sa.Text(), nullable=True),
    sa.Column('tool_input', sa.Text(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('tool_process_data', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('message_token', sa.Integer(), nullable=True),
    sa.Column('message_unit_price', sa.Numeric(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answer_token', sa.Integer(), nullable=True),
    sa.Column('answer_unit_price', sa.Numeric(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='message_agent_thought_pkey')
    )
    with op.batch_alter_table('message_agent_thoughts', schema=None) as batch_op:
        batch_op.create_index('message_agent_thought_message_chain_id_idx', ['message_chain_id'], unique=False)
        batch_op.create_index('message_agent_thought_message_id_idx', ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_agent_thoughts', schema=None) as batch_op:
        batch_op.drop_index('message_agent_thought_message_id_idx')
        batch_op.drop_index('message_agent_thought_message_chain_id_idx')

    op.drop_table('message_agent_thoughts')
    # ### end Alembic commands ###
