"""conversation

Revision ID: 32f08ad5ec8c
Revises: 62c0d0824348
Create Date: 2025-12-20 10:52:03.104181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f08ad5ec8c'
down_revision = '62c0d0824348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('app_model_config_id', sa.UUID(), nullable=False),
    sa.Column('model_provider', sa.String(length=255), nullable=False),
    sa.Column('override_model_configs', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('system_instruction', sa.Text(), nullable=True),
    sa.Column('system_instruction_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('from_source', sa.String(length=255), nullable=False),
    sa.Column('from_end_user_id', sa.UUID(), nullable=True),
    sa.Column('from_account_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('read_account_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='conversation_pkey')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('conversation_app_from_user_idx', ['app_id', 'from_source', 'from_end_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('conversation_app_from_user_idx')

    op.drop_table('conversations')
    # ### end Alembic commands ###
