"""sites

Revision ID: 54dcdc267ce3
Revises: 1d44e14e05e8
Create Date: 2025-12-20 11:12:35.864283

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '54dcdc267ce3'
down_revision = '1d44e14e05e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('icon_background', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('default_language', sa.String(length=255), nullable=False),
    sa.Column('copyright', sa.String(length=255), nullable=True),
    sa.Column('privacy_policy', sa.String(length=255), nullable=True),
    sa.Column('customize_domain', sa.String(length=255), nullable=True),
    sa.Column('customize_token_strategy', sa.String(length=255), nullable=False),
    sa.Column('prompt_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=255), server_default=sa.text("'normal'::character varying"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name='site_pkey')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index('site_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('site_code_idx', ['code', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index('site_code_idx')
        batch_op.drop_index('site_app_id_idx')

    op.drop_table('sites')
    # ### end Alembic commands ###
